name: delicias_darsy_movil
description: "A new Flutter project for DeliciaSoft bakery management."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Utilidades y JSON
  intl: ^0.18.1
  json_annotation: ^4.8.1

  # Estado y preferencias
  provider: ^6.0.5
  shared_preferences: ^2.2.2

  # UI y estilos
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4

  # Red e internet
  http: ^1.1.0
  connectivity_plus: ^5.0.2

  # Formularios y validaciÃ³n
  form_field_validator: ^1.1.0
  email_validator: ^2.1.17

  # Manejo de imÃ¡genes
  image_picker: ^1.1.2

  # Google Maps y geolocalizaciÃ³n
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.0
  geolocator: ^10.1.0
  google_places_flutter: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1  # ðŸ‘ˆ aquÃ­ va este paquete

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo.png
